spring:
  redis:
    host: 192.168.194.128
zuul:
  #全部服务都可以传递cookies
  sensitive-headers:
  routes:
    #自定义路由
#    myProduct:
#      path: /myProduct/**
#      serviceId: product
    #将敏感头过滤set设置为空 即可传递cookie sensitiveHeaders:
    #简便写法
    product: /myProduct/**
  #禁止路由设置
  ignored-patterns:
    - /**/product/listForOrder
management:
  endpoints:
    web:
      exposure:
        include: routes,filters
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
